import "server-only";

/**
 * جدول مسارات الـ API للاستدعاء الداخلي من serverFetch (بدون HTTP).
 * أي route جديد تحت app/api لازم يتضاف هنا، وإلا serverFetch من الـ Server Components
 * هيرمي خطأ (الاختبار tests/unit/domain.test.ts بيتأكد إن الجدول كامل).
 */

type RouteModule = Record<string, unknown>;

export const API_ROUTES: { pattern: string; load: () => Promise<RouteModule> }[] = [
  { pattern: "/api/accounting/[id]", load: () => import("@/app/api/accounting/[id]/route") },
  { pattern: "/api/accounting/assets/[id]", load: () => import("@/app/api/accounting/assets/[id]/route") },
  { pattern: "/api/accounting/assets", load: () => import("@/app/api/accounting/assets/route") },
  { pattern: "/api/accounting/exchange", load: () => import("@/app/api/accounting/exchange/route") },
  { pattern: "/api/accounting/manual", load: () => import("@/app/api/accounting/manual/route") },
  { pattern: "/api/accounting/overview", load: () => import("@/app/api/accounting/overview/route") },
  { pattern: "/api/accounting", load: () => import("@/app/api/accounting/route") },
  { pattern: "/api/accounting/summary", load: () => import("@/app/api/accounting/summary/route") },
  { pattern: "/api/auth/login", load: () => import("@/app/api/auth/login/route") },
  { pattern: "/api/auth/logout", load: () => import("@/app/api/auth/logout/route") },
  { pattern: "/api/auth/me/change-password", load: () => import("@/app/api/auth/me/change-password/route") },
  { pattern: "/api/auth/me", load: () => import("@/app/api/auth/me/route") },
  { pattern: "/api/auth/me/update", load: () => import("@/app/api/auth/me/update/route") },
  { pattern: "/api/auth/request-reset", load: () => import("@/app/api/auth/request-reset/route") },
  { pattern: "/api/categories/[id]", load: () => import("@/app/api/categories/[id]/route") },
  { pattern: "/api/categories", load: () => import("@/app/api/categories/route") },
  { pattern: "/api/customers/[id]", load: () => import("@/app/api/customers/[id]/route") },
  { pattern: "/api/customers", load: () => import("@/app/api/customers/route") },
  { pattern: "/api/dashboard/overview", load: () => import("@/app/api/dashboard/overview/route") },
  { pattern: "/api/exchange-rates/current", load: () => import("@/app/api/exchange-rates/current/route") },
  { pattern: "/api/exchange-rates", load: () => import("@/app/api/exchange-rates/route") },
  { pattern: "/api/inventory/adjustments", load: () => import("@/app/api/inventory/adjustments/route") },
  { pattern: "/api/inventory/movements", load: () => import("@/app/api/inventory/movements/route") },
  { pattern: "/api/inventory/opening-stock", load: () => import("@/app/api/inventory/opening-stock/route") },
  { pattern: "/api/accounting/opening-balances", load: () => import("@/app/api/accounting/opening-balances/route") },
  { pattern: "/api/inventory/products/[id]/movements", load: () => import("@/app/api/inventory/products/[id]/movements/route") },
  { pattern: "/api/inventory", load: () => import("@/app/api/inventory/route") },
  { pattern: "/api/notifications/check-overdue-tailoring", load: () => import("@/app/api/notifications/check-overdue-tailoring/route") },
  { pattern: "/api/notifications", load: () => import("@/app/api/notifications/route") },
  { pattern: "/api/products/[id]", load: () => import("@/app/api/products/[id]/route") },
  { pattern: "/api/products", load: () => import("@/app/api/products/route") },
  { pattern: "/api/purchases/[id]/payments", load: () => import("@/app/api/purchases/[id]/payments/route") },
  { pattern: "/api/purchases/[id]", load: () => import("@/app/api/purchases/[id]/route") },
  { pattern: "/api/purchases/[id]/status", load: () => import("@/app/api/purchases/[id]/status/route") },
  { pattern: "/api/purchases", load: () => import("@/app/api/purchases/route") },
  { pattern: "/api/reports/export", load: () => import("@/app/api/reports/export/route") },
  { pattern: "/api/reports", load: () => import("@/app/api/reports/route") },
  { pattern: "/api/sales/[id]", load: () => import("@/app/api/sales/[id]/route") },
  { pattern: "/api/sales/checkout", load: () => import("@/app/api/sales/checkout/route") },
  { pattern: "/api/sales/invoices/[id]", load: () => import("@/app/api/sales/invoices/[id]/route") },
  { pattern: "/api/sales/orders/[id]/cancel", load: () => import("@/app/api/sales/orders/[id]/cancel/route") },
  { pattern: "/api/sales/orders/[id]", load: () => import("@/app/api/sales/orders/[id]/route") },
  { pattern: "/api/sales/orders", load: () => import("@/app/api/sales/orders/route") },
  { pattern: "/api/sales/products", load: () => import("@/app/api/sales/products/route") },
  { pattern: "/api/sales", load: () => import("@/app/api/sales/route") },
  { pattern: "/api/suppliers/[id]", load: () => import("@/app/api/suppliers/[id]/route") },
  { pattern: "/api/suppliers", load: () => import("@/app/api/suppliers/route") },
  { pattern: "/api/tailoring/commission-payments", load: () => import("@/app/api/tailoring/commission-payments/route") },
  { pattern: "/api/tailoring/orders/[id]/cancel", load: () => import("@/app/api/tailoring/orders/[id]/cancel/route") },
  { pattern: "/api/tailoring/orders/[id]/convert-to-product", load: () => import("@/app/api/tailoring/orders/[id]/convert-to-product/route") },
  { pattern: "/api/tailoring/orders/[id]/edit", load: () => import("@/app/api/tailoring/orders/[id]/edit/route") },
  { pattern: "/api/tailoring/orders/[id]/pickup", load: () => import("@/app/api/tailoring/orders/[id]/pickup/route") },
  { pattern: "/api/tailoring/orders/[id]/production-receive", load: () => import("@/app/api/tailoring/orders/[id]/production-receive/route") },
  { pattern: "/api/tailoring/orders/[id]/refund", load: () => import("@/app/api/tailoring/orders/[id]/refund/route") },
  { pattern: "/api/tailoring/orders/[id]", load: () => import("@/app/api/tailoring/orders/[id]/route") },
  { pattern: "/api/tailoring/orders/[id]/status", load: () => import("@/app/api/tailoring/orders/[id]/status/route") },
  { pattern: "/api/tailoring/orders", load: () => import("@/app/api/tailoring/orders/route") },
  { pattern: "/api/upload", load: () => import("@/app/api/upload/route") },
  { pattern: "/api/users/[id]", load: () => import("@/app/api/users/[id]/route") },
  { pattern: "/api/users", load: () => import("@/app/api/users/route") },
];
